# fly.toml app configuration file generated for county-city-zip-tool on 2026-05-31T01:59:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'county-city-zip-tool'
primary_region = 'dfw'

[env]
  CANONICAL_HOST = "citycountyzip.randometc.org"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
